replicaCount: 3

image:
  repository: kossvrn/kossvrn
  pullPolicy: IfNotPresent
  tag: "1.0.0"

podLabels: maven

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30001
  

resources: {}

livenessProbe:
  httpGet:
    path: /demo
    port: 8080
readinessProbe:
  httpGet:
    path: /demo
    port: 8080


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
